### ISSUE TITLE
Remove `--tmp` from Substrate node command-line instructions

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1007]
Follow-up to https://github.com/paritytech/substrate/pull/9938.

tl;dr: `--dev` now implies `--tmp`.

## ToDo
- [ ] Review `ink-waterfall`.
- [ ] Review `ink-docs`.
- [ ] Review [workshop](https://docs.substrate.io/tutorials/v3/ink-workshop/pt1/).
- [ ] Update `/assets/tutorials/ink-workshop/start-canvas-node.png` screenshot in workshop.
- [ ] Review `substrate-contracts-node`.
- [ ] Review `canvas`.
- [ ] Review `cargo-contract`.

**Comment by HCastano** [comment]
I opened a few PRs just now to close this out
