### ISSUE TITLE
Review our examples for usage of the return type `Result`

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1045]
This issue is blocked by https://github.com/polkadot-js/apps/issues/6465 ‒ the UI currently does not display that an error occurred when a call returns `Result::Err` and is reverted.

## ToDo

- [ ] Review the usage of `assert!` in our examples and  migrate those potentially to `Result::Err`.
- [ ] There are a number of examples which already use `Result` as a return type. We should check if the usage of `Result` there is actually correct. When those examples were written there was not yet our "Revert the transaction if the ink! message returns `Result::Err`" behavior.
- [ ] The inverse of [this commit](https://github.com/paritytech/ink/pull/1020/commits/21bb5585f9235e57eb5843383c991f3818591c45) should be merged, it already implements `Result::Err` for our `proxy` example.
