### ISSUE TITLE
Implement `seal_set_code_hash` and add example contract

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1185]
I've marked this issues as a good first one since the task is something that can be done mostly analog to already existing code.

ink! interfaces with Substrate's [`contracts` pallet](https://github.com/paritytech/substrate/tree/master/frame/contracts) via an API. The API functions are named with the prefix `seal_` ‒ so e.g. `seal_call`. From time to time new API functions are added. One recently added one is `seal_set_code_hash`, you can find it here: https://github.com/paritytech/substrate/blob/master/frame/contracts/src/wasm/runtime.rs#L1976-L2011. It was added in https://github.com/paritytech/substrate/issues/10567.

While the `contracts` pallet side has been implemented we are missing a possibility to invoke this function from ink!.

## ToDo

- [ ] Add a new function `ink_env::set_code_hash`.
Take a look at the file [`env/src/api.rs`](https://github.com/paritytech/ink/blob/master/crates/env/src/api.rs), it should be possible to take one of the functions there (e.g. `is_contract`) and implement this new function analog.
- [ ] You will have to add `seal_set_code_hash` in this file: https://github.com/paritytech/ink/blob/master/crates/env/src/engine/on_chain/ext.rs#L341. Add it as an `__unstable__` function there.
- [ ] You can ignore off-chain testing for now and add an `unimplemented!("off-chain environment does not yet support …");` there.
- [ ] Add an example which illustrates how this new function can be used to write an upgradeable smart contract.
