### ISSUE TITLE
Add example of how to call a Solang Solidity contract from ink!

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1228]
## ToDo

- [ ] Solang should generate the same selectors as ink! (@xgreenx mentioned this a while ago, is there by chance already an issue in the Solang repo?)
- [ ] Solang should generate `contract-interface.rs` with a trait that exposes the contract methods.
- [ ] The example should demonstrate cross-contract calls.

Blocked by https://github.com/paritytech/cargo-contract/issues/526.

**Comment by HCastano** [comment]
@xermicus assigning you since you're in the best position to (eventually) close this
