### ISSUE TITLE
Add `default` attribute for constructors and messages

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1703]
I would like the possibility of optionally annotating a default constructor/message for a contract.

This is inspired by workshops, where we had all kinds of mishaps because people submitted transactions with the first constructor/message selected in the dropdown. Having this functionality for messages/constructors that are supposed to be used during workshops will make the life of everyone easier and reduce the source for confusion.

See here how the default selection looks for `ink-workshop/game`:

![screenshot-contracts-ui substrate io-2023 03 03-19_00_23](https://user-images.githubusercontent.com/241530/222794120-5d9902b2-678f-4d00-938d-6e30486efd2e.png)

We had a lot of people confused by the immediate red error `Contract Trapped` because `destroy()` (a privileged method) is selected by default.

## ToDo

- [x] Add a new ink! attribute `default` that is optional and can be used exactly once for a constructor and once for a message.
- [x] Reflect this information in the metadata. Just add a field `default: bool` for the `message` or `constructor` object:
```json
      {                    
        "args": [],    
        "default": true,      
        "docs": [
          " Flips the current value of the Flipper's boolean."
        ],                 
        "label": "flip",              
        "mutates": true,     
        "payable": false,                                                      
        "returnType": { 
          "displayName": [   
            "ink",           
            "MessageResult"
          ],               
          "type": 1        
        },           
        "selector": "0x633aa551"
      },   
```
- [x] Create a follow-up issue for Contracts UI and `polkadot-js` to choose this entry by default for constructors/messages.
- [x] Create a follow-up issue (or PR, if you're up for it) for [`ink-docs`](https://github.com/paritytech/ink-docs) to extend the documentation of https://use.ink/basics/metadata.

**Comment by kziemianek** [comment]
Hi @cmichi , I would like to take this task.

**Comment by SkymanOne** [comment]
> Hi @cmichi , I would like to take this task.

Hi. No one currently works on this issue. You are more than welcome to tackle it and create a PR. We will be happy to review it and give other assistance if necessary.

**Comment by kziemianek** [comment]
Hi, I've opened pull request with required changes.  I've also resolved few conflicts with commits ugrading syn to version 2. Could you please take a look, there are several changes to be done in downstream projects, the first one is https://github.com/polkadot-js/api .

**Comment by SkymanOne** [comment]
Closing as all the tasks have been completed. Thank you @kziemianek for your contribution!

**Comment by kziemianek** [comment]
@SkymanOne thanks for collaboration!
