### ISSUE TITLE
Add script to synchronize `integration-test` folder with `ink-examples` repo

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1754]
### ToDo

- [ ] Please add a script to `scripts/` that copies the `integration-tests/*` folders over to a specified folder. 
- [ ] All dependencies on relative paths (e.g. `ink = ".../../ink"`) should be changed to refer to the latest version of the published crate.
- [ ] We exclude some `integration-tests` from copying them over. Please exclude those folders in the script. You can check which ones are left out by looking at the ones missing on https://github.com/paritytech/ink-examples.
- [ ] Please add an entry to the release checklist to copy the `integration-tests` over to the `ink-examples` repository using the above script.
