### ISSUE TITLE
Re-export `scale` and `scale-info` from `ink` entrance crate

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#1885]
## ToDo's

- [ ] `#[storage_item]` should be adapted to use `Encode` and `Decode` and `type-info` with crate prefixes. Same for Andrew's Events 2.0 macros. 
- [ ] Create `ink::Encode`, `ink::Decode`, `ink::Codec` and re-export `scale::{Encode, Decode, Codec}`.
- [ ] Remove check for compatible scale versions in `cargo-contract`.
