### ISSUE TITLE
Additional contract metadata

### ISSUE THREAD

**Issue by ascjones** [paritytech/ink#299]
As discussed in https://github.com/paritytech/ink/pull/296#issuecomment-564531512.

Add extra data to at the `InkProject` struct level. e.g.

- `version` as suggested by @jacogr 
- `language` e.g. `ink!`
- Hashes over the code to properly infer if the supplied code matches the metadata
- the author of the contract to make it possible to contact maintainers
- the used Rust (or other compiler) version to have "more deterministic" way to rebuild the contract
- etc.

**Update:** see https://github.com/paritytech/ink/issues/299#issuecomment-651132343 below with outcome of meeting with @Robbepop @seanyoung

## todo:

- [x] `scale-info`
  - [x] remove string table (https://github.com/paritytech/scale-info/pull/17)
  - [x] release `v0.3.0`
- [x] `ink!`
  - [x] ~~Define types and add to `InkProject` struct~~, 
  - [x] ~~Accept instances of contract metadata types via `_ink_generate_metadata`~~
  - [x] Merge https://github.com/paritytech/ink/pull/467
- [x] `cargo-contract`
  - [x] Extract ink contract metadata as json via call to extern `_ink_generate_metadata`
  - [x] Combine with additional metadata extracted from cargo metadata
  - [x] Merge https://github.com/paritytech/cargo-contract/pull/62

**Comment by Robbepop** [comment]
For `version` we might just use the one we already have in the ink! macro header and its value should be a string with the following formatting:
```
version: "0.1.0"
```

Also we might be interested in the underlying compiler, so we might want to include the Rust version into `version` somehow.
For `language` we might want to use `ink!` for an ink! project. Its value is simply a string:
```
language: "ink!"
```

Not sure how we are going to compute the hashes but we should standardize a specific hash for that first.
The `authors` field should be an array of `string` where `string` should have the following formatting (as in Cargo):
```
username <user@email.domain>
```
So we end up having something like:
```
authors:  [ foo <foo@bar.baz>, qed <qed.boom@meow.woof> ]
```

Also we maybe even want the date of creation of the metadata:
```
date: "2019-12-31"
```

Maybe even a description of the whole contract might be handy:
```
description: "This is my description of what this contract does and does not."
```

**Comment by seanyoung** [comment]
How about including the compiler version in the string which identifies the compiler.

```
compiler: "solang 0.1.0 (llvm 8.0.1)"
```

which could also be:

```
compiler: "ink! 2.0 (rust 1.33.0)"
```

**Comment by seanyoung** [comment]
I think some sort of link back to source code would be great. We could include the repo, but also the commit and filename? Or should that be part of the link itself.
```
src = [ "https://github.com/foo/bar/baz.sol",  "https://github.com/foo/bar/bax.sol" ]
```

**Comment by Robbepop** [comment]
We just had an audio call with the following extensional metadata support aggrement:

- `hash`: of the Wasm file using BLAKE2 256-bit
- URL for new version query
- `source_language`: e.g. Solidity, AssemblyScript or Rust (including version X.Y.Z (semantic versioning))
- `source_compiler`: e.g. Solang, ink!/Rust (including version X.Y.Z (semantic versioning))
- `name`: Identifier for the smart contract name. (https://crates.io/crates/unicode-xid)
- `version`: Semantic version field for the smart contract.
- `authors`: Non-empty sequence of strings.
- `description:` Optional short description about the smart contract.
- `documentation`: Optional URL to link to API-level documentation of the smart contract.
- `repository`: Optional URL to link to the repository.
- `homepage`: Optional URL to link to the smart contract's associated homepage.
- `license`: Optional field to identify the license of the smart contract given in SPDX license list 3.6 format OR a URL to a user provided non-standard license.

**Comment by ascjones** [comment]
First auto-generated json of the new format (with hardcoded values)
```
{
  "metadata_version": "0.1.0",
  "source": {
    "hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "language": "ink! 2.1.0",
    "compiler": "ink! 2.1.0 (rustc 1.46.0)"
  },
  "contract": {
    "name": "testing",
    "version": "0.1.0",
    "authors": [
      "author@example.com"
    ],
    "documentation": "http://example.com/"
  },
  "spec": {
    "types": [
      {
        "def": {
          "primitive": "i32"
        }
      }
    ],
    "storage": {
      "Struct": {
        "fields": [
          {
            "name": "value",
            "layout": {
              "Cell": {
                "key": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "ty": 1
              }
            }
          }
        ]
      }
    },
    "spec": {
      "name": "incrementer",
      "constructors": [
        {
          "name": "new",
          "selector": "0x41e691fc",
          "args": [
            {
              "name": "init_value",
              "type": {
                "id": 1,
                "displayName": [
                  "i32"
                ]
              }
            }
          ],
          "docs": []
        },
        {
          "name": "default",
          "selector": "0xcfee7c08",
          "args": [],
          "docs": []
        }
      ],
      "messages": [
        {
          "name": "inc",
          "selector": "0x37b82f69",
          "mutates": true,
          "args": [
            {
              "name": "by",
              "type": {
                "id": 1,
                "displayName": [
                  "i32"
                ]
              }
            }
          ],
          "returnType": null,
          "docs": []
        },
        {
          "name": "get",
          "selector": "0x6817c00f",
          "mutates": false,
          "args": [],
          "returnType": {
            "id": 1,
            "displayName": [
              "i32"
            ]
          },
          "docs": []
        }
      ],
      "events": [],
      "docs": []
    }
  }
}
```

**Comment by ascjones** [comment]
New updated metadata:

```
{
  "metadata_version": "0.1.0",
  "source": {
    "hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "language": "ink! 2.1.0",
    "compiler": "rustc 1.46.0"
  },
  "contract": {
    "name": "testing",
    "version": "0.1.0",
    "authors": [
      "author@example.com"
    ],
    "documentation": "http://example.com/"
  },
  "storage": {
    "name": "Incrementer",
    "layout": {
      "Struct": {
        "fields": [
          {
            "name": "value",
            "layout": {
              "Cell": {
                "key": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "ty": 1
              }
            }
          }
        ]
      }
    }
  },
  "spec": {
    "constructors": [
      {
        "name": "new",
        "selector": "0x41e691fc",
        "args": [
          {
            "name": "init_value",
            "type": {
              "id": 1,
              "displayName": [
                "i32"
              ]
            }
          }
        ],
        "docs": []
      },
      {
        "name": "default",
        "selector": "0xcfee7c08",
        "args": [],
        "docs": []
      }
    ],
    "messages": [
      {
        "name": "inc",
        "selector": "0x37b82f69",
        "mutates": true,
        "args": [
          {
            "name": "by",
            "type": {
              "id": 1,
              "displayName": [
                "i32"
              ]
            }
          }
        ],
        "returnType": null,
        "docs": []
      },
      {
        "name": "get",
        "selector": "0x6817c00f",
        "mutates": false,
        "args": [],
        "returnType": {
          "id": 1,
          "displayName": [
            "i32"
          ]
        },
        "docs": []
      }
    ],
    "events": [],
    "docs": []
  }
}
```

**Comment by Robbepop** [comment]
Looking good so far!

**Reminder:** That `name` on `storage` (here `Incrementer`) is actually an ink! detail information.
In ink! it is kind of nice to know about it but I am not sure about this for Solidity (Solang) or other languages.
Maybe we need to encode this into `user` but I will talk to @seanyoung first.

**Comment by ascjones** [comment]
Could make it an optional field?

**Comment by Robbepop** [comment]
Wait for action until we resolved this with @seanyoung please.

**Comment by seanyoung** [comment]
The `name` on `storage` isn't something that necessarily makes sense with Solidity. It could be populated with the contract name (so same as `contract.name`).

**Comment by ascjones** [comment]
Generated for incrementer with no hardcoded values:

```
{
  "metadata_version": "0.1.0",
  "source": {
    "hash": "0x4aa82d1faa733477c06424b3d67d9fa0a40f5aa7a34877f811652ab33e8b5d1b",
    "language": "ink! 2.1.0",
    "compiler": "rustc 1.46.0-nightly"
  },
  "contract": {
    "name": "incrementer",
    "version": "2.1.0",
    "authors": [
      "Parity Technologies <admin@parity.io>"
    ],
    "documentation": "http://docs.rs/",
    "homepage": "http://homepage.rs/"
  },
  "user": {
    "more-user-provided-fields": [
      "and",
      "their",
      "values"
    ],
    "some-user-provided-field": "and-its-value"
  },
  "spec": {
    "constructors": [
      {
        "args": [
          {
            "name": "init_value",
            "type": {
              "displayName": [
                "i32"
              ],
              "id": 1
            }
          }
        ],
        "docs": [],
        "name": "new",
        "selector": "0x41e691fc"
      },
      {
        "args": [],
        "docs": [],
        "name": "default",
        "selector": "0xcfee7c08"
      }
    ],
    "docs": [],
    "events": [],
    "messages": [
      {
        "args": [
          {
            "name": "by",
            "type": {
              "displayName": [
                "i32"
              ],
              "id": 1
            }
          }
        ],
        "docs": [],
        "mutates": true,
        "name": "inc",
        "returnType": null,
        "selector": "0x37b82f69"
      },
      {
        "args": [],
        "docs": [],
        "mutates": false,
        "name": "get",
        "returnType": {
          "displayName": [
            "i32"
          ],
          "id": 1
        },
        "selector": "0x6817c00f"
      }
    ]
  },
  "storage": {
    "layout": {
      "Struct": {
        "fields": [
          {
            "layout": {
              "Cell": {
                "key": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "ty": 1
              }
            },
            "name": "value"
          }
        ]
      }
    },
    "name": "Incrementer"
  },
  "types": [
    {
      "def": {
        "primitive": "i32"
      }
    }
  ]
}
```

**Comment by Robbepop** [comment]
Very nice!

How was the `user` data provided in this case?
```
"user": {
    "more-user-provided-fields": [
      "and",
      "their",
      "values"
    ],
    "some-user-provided-field": "and-its-value"
  },
```

Also due to the upcoming trait support we might have the need to find some ground rules or changes for message and constructor names since they now can overlap for ink!.

**Comment by ascjones** [comment]
```
[package.metadata.contract.user]
some-user-provided-field = "and-its-value"
more-user-provided-fields = ["and", "their", "values"]
```

**Comment by ascjones** [comment]
**WIP comment**. Continuing a conversation I had with @Robbepop https://github.com/paritytech/cargo-contract/pull/62#discussion_r451634904.

The question is: where the data structures which define the additional metadata (generated by `cargo-contract`), and combine it with the contract metadata (generated by `ink_lang`), should live. 

## Current status

`ink_metadata` defines a struct which contains contract metadata about the ABI and the storage layout:

```
/// An entire ink! project for metadata file generation purposes.
#[derive(Debug, Serialize)]
pub struct InkProject {
    #[serde(flatten)]
    registry: Registry,
    #[serde(rename = "storage")]
    layout: layout2::StorageLayout<CompactForm>,
    spec: ContractSpec<CompactForm>,
}
```

`ink_lang` generates an instance of this which is serialized and written to a file by an auto-generated binary in `cargo-contract`: https://github.com/paritytech/cargo-contract/blob/master/templates/tools/generate-metadata/main.rs

## Options

### 1, Define in `ink_metadata`

**todo:** pros/cons

### 2. Define in `cargo-contract`

**todo:** pros/cons

**Comment by ascjones** [comment]
@seanyoung an idea that @Robbepop and I discussed: we could extract the [types](https://github.com/paritytech/cargo-contract/blob/4148a33c1393c9bf483216d139dba47d92c4659c/src/cmd/metadata/contract.rs) which define the extended metadata into their own crate, which `solang` could use. This would avoid duplication and ensure consistency.

**Comment by seanyoung** [comment]
@ascjones that is a great solution, I like it very much!

There is some precedent for a crate which just defines types. For example https://github.com/gluon-lang/lsp-types does this for the Language Server protocol.

**Comment by Robbepop** [comment]
sorry :see_no_evil:

**Comment by Robbepop** [comment]
This has been implemented and is available with ink! 3.0. Closed.
