### ISSUE TITLE
Add performance tests for ink_primitive::Key and KeyPtr

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#402]
On every smart contract execution we have to compute several `Key` instances and "pointer" arithmetic on them. Sadly we cannot yet offload this at compile-time where it should be.

This is why we need to make sure that those methods we have to execute always are as cost efficient as possible. For this reason we want to have benchmarks to test especially the two main components here:

- `ink_primitives::Key`
- `ink_core::storage2::traits::KeyPtr`

This issues is about creating initial performance tests using the `criterion` crate.
Also the implementer might improve `Key` and `KeyPtr` or related methods and procedures if an inefficiency is found.

Later the benchmarks should be integrated into the CI pipeline where they are used to find potential regressions upon commits and PRs.

## ToDo List

- [x] Write benchmark and performance tests using `criterion`.
- [x] Find weak spots in the current implementation, document it and improve them.
- [ ] Integrate the performance testing into the GitLab CI as a new job. (Ask @TriplEight for help with that.) 
- [x] **Bonus:** It might be interesting research to try out new internal structure for `Key`, e.g. `[u64; 4]` instead of `[u8; 32]` since our smart contracts operate on Wasm which has only 32-bit and 64-bit integers but real `u8` representation. It is going to be important in this case that serialization and deserialization as well as conversion between byte buffers stay correct.

**Comment by TriplEight** [comment]
it would also make sense to compare previous benches and warn/fail if performance drops.

**Comment by Robbepop** [comment]
Started implementation in https://github.com/paritytech/ink/pull/433.

**Comment by Robbepop** [comment]
The only thing left for this ticket is integration into CI which could probably be put into yet another more explicit issue. Closed.
