### ISSUE TITLE
Add more unit tests for storage2 primitive implementations

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#403]
One of the few unit tests that have been left out of the initial implementation of the `storage2` module have been unit tests that check if the provided implementation of all Rust primitives, arrays, tuples and prelude types is actually correct.

These implementations are critical enough that they should not be taken for granted.
This issue is about writing unit tests for their `SpreadLayout` and `PackedLayout` implementations.

A show case for unit tests of all Rust primitives such as `i32` and also ink! primitives such as `Key` does already exist and can be taken as inspiration.

## ToDo List

- [ ] Get familiar with writing unit tests using the already existing unit tests for ink! and Rust primitives for `SpreadLayout` and `PackedLayout`.
    - Find them here: https://github.com/paritytech/ink/blob/master/core/src/storage2/traits/impls/prims.rs#L236
- [ ] Write unit tests for Rust arrays.
- [ ] Write unit tests for Rust tuples.
- [ ] Write unit tests for Rust's `Option` and `Result` types.
- [ ] Write unit tests for the rest prelude types, e.g. `Box`, `BTreeMap`, etc.
