### ISSUE TITLE
Add PushOnDrop storage2 abstraction

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#405]
This issue is about adding the `PushOnDrop` utility abstraction for the `storage2` module.

The `PushOnDrop` abstraction serves a single but commonly useful purpose:
It wraps a single `T` with `T: SpreadLayout` just like `ManuallyDrop` does but instead of calling `drop` upon ending its lifetime it pushes its internal storage onto the contract storage. For that purpose it also needs to own or access a `Key`.

This is useful for two different use sites:

1. The dynamic storage allocator for Wasm compilations.
2. The static storage fields of a smart contract later to be used by `ink_lang` generated code.

We don't want this to be applied for the off-chain environment for the dynamic storage allocator since that would harm testability of our framework when run on a single thread.

The downside of this approach is that it leaks memory upon `drop`. However, for Wasm and its mentioned usages this doesn't matter since these entities usually end their lifes together with the smart contract execution. So instead of the contract itself cleaning up its memory it is the host's job which also saves a small amount of gas.

The implementation looks roughly like this:

```rust
pub struct PushOnDrop<T>
where
    T: SpreadLayout,
{
    at: Key,
    what: ManuallyDrop<T>,
}

impl<T> PushOnDrop<T>
where
    T: SpreadLayout,
{
    fn new(at: Key, what: T) -> Self { ... }
    fn get(this: &Self) -> &T { ... }
    fn get_mut(this: &mut Self) -> &mut T { ... }
}

impl<T> Deref for PushOnDrop<T>
where
    T: SpreadLayout,
{
    type Target = T;
    fn deref(&self) -> &Self::Target { ... }
}

impl<T> DerefMut for PushOnDrop<T>
where
    T: SpreadLayout,
{
    fn deref_mut(&mut self) -> &mut Self::Target { ... }
}

impl<T> Drop for PushOnDrop<T>
where
    T: SpreadLayout,
{
    fn drop(&mut self) {
        push_spread_root::<T>(&*what, &self.at);
    }
}

... // and probably some more trait implementations just like Memory<T> or Pack<T>
```

## ToDo List

- [ ] Implement `PushOnDrop` with its 2 inherent methods and its special `Drop` impl.
    Put its implementation file at best next to `memory.rs` and `pack.rs`.
- [ ] Implement the rest of the standard trait implementations.
- [ ] Write unit tests for `PushOnDrop` to test its functionality.
- [ ] Integrate `PushOnDrop` usage for the Wasm-based dynamic storage allocator.

**Comment by Robbepop** [comment]
Closed since not a good or useful abstraction.
