### ISSUE TITLE
Add new operations to storage2::Vec

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#406]
The `storage2::Vec` is pretty basic so far.
It lacks some operations to efficiently override existing elements of it if there is no requirement to read the state of the overridden elements.

Currently we can only do some `*vec.get_mut(i).unwrap() = a;` or `vec[i] = a;` but this might incur a read on the i-th element and thus might execute a storage read which is comparable to a database read. We really want to prevent this from happening and instead want to provide users with a new more efficient API that they can use.

## New API

```rust
/// Sets the elements at the given index to the new value.
///
/// Won't return the old element back to the caller.
/// Prefer this operation over other method of overriding an element
/// in the storage vector since this is more efficient.
fn set(&mut self, index: Index, new_value: T) { ... }
```

With the new `set` operation in mind we can also support another more efficient API to clear up the storage vector in case that is ever needed. Currently we do not support `vec.clear()` and instead require users to remove all the elements via `pop` operations.
This is insanely inefficient since it will perform a data base read for all elements in the vector and also will touch the vectors length many times.
Instead we introduce a `clear` method that utilizes the same underlying technique as the new `set` method in order to clean up the storage and then also sets the vector's length to zero afterwards. The only interaction with the storage is to clean up all the cleared cells and change length to zero - so just write operations which are generally preferred over read operations on the storage.

Both, the `set` and `clear` operations will work on the `LazyIndexMap::set` API.

## ToDo List

- [ ] Implement `storage::Vec::set`.
- [ ] Implement unit tests for `storage::Vec::set`.
- [ ] Implement `storage::Vec::clear`.
- [ ] Implement unit tests for `storage::Vec::clear`.
- [ ] **Bonus**: Write some benchmarks that prove the point of their gained efficiency.
