### ISSUE TITLE
Port storage::BinaryHeap to storage2

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#410]
The new `storage2` module is missing the important `BinaryHeap` that operates efficiently on contract storage.
It has been implemented by @cmichi in the past for the old `storage` module and needs to be ported with some adjustments over to `storage2`. Of course, if needed also a rewrite is possible here and might be useful since all `storage2` data structure have been complete rewrites so far to accomodate for the new requirements around the new traits and new low-level lazy data structures.

Also we might want to add some new APIs to the `storage::BinaryHeap`.
So, what is going to be needed for this ...

## Internal Structure

Similar to the `storage2::Vec` the `storage2::BinaryHeap` should be based on the low-level `LazyIndexMap` and should require a `len` field of type `Lazy<u32>` to store the number of elements that are currently stored in the storage binray heap.

## ToDo List

Subsets of this ToDo list can suffice to craft a PR so we can implement the `storage2::BinaryHeap` in many PRs incrementally.

- [ ] Implement `BinaryHeap` for the `storage2` module with the following methods:
    - [x] `new`: Creates a new `BinaryHeap` for contract inistantiation purposes (see other data structures for `storage2` as examples)
    - [x] `len`: Returns the current length of the binary heap.
    - [x] `is_empty`: Returns `true` if the binray heap is empty.
    - [x] `peek`: Returns a shared reference to the greatest element of the binary heap if any.
    - [x] `peek_mut`: Returns an exclusive reference to the greatest element of the binary heap if any.
    - [x] `push`: Pushes the given element to the binary heap.
    - [x] `pop`: Pops the greatest element from the binary heap.
    - [x] `iter`: Iterates over the values of the binary heap.
        Strangely the old `storage::BinaryHeap` has two iterator methods `iter` and `values` but I think we only need `iter`.
    - [x] **Bonus:** `clear`: Clears all elements from the binary heap.
- [ ] Implement all important standard Rust traits for the `storage2::BinaryHeap`:
    - [x] `Default`: For simply contract instantiation.
    - [x] `Debug`: Should be derivable.
    - [x] `PartialEq` + `Eq` if `T: PartialEq` and `T: Eq`: Mostly important for testing but anyways nice to have in general.
    - [x] `Drop`: Must be implemented in order to command the underlying `LazyIndexMap` to clear its cells. For an example how to implement this properly take a look at the `storage2::Vec`.
    - [x] `Extend` and `FromIterator`: Useful traits to initialize a `storage2::BinaryHeap` from an iterator.
    - [ ] `IntoIterator` for `&BinaryHeap` and `&mut BinaryHeap`: Generally useful for testing but also nice to have in general.
- [x] Implement `SpreadLayout` trait for the `storage2::BinaryHeap`.
- [x] Implement unit tests for the `storage2::BinaryHeap`.
    - For an inspiration look at the unit tests provided for the other `storage2` data structure.
- [x] **Bonus:** Add performance tests for the `storage2::BinaryHeap` using the `criterion` crate.
- [ ] **Bonus:** Add optimizations to merge child elements to use the same storage entry. This is useful since most often both child elements are accessed together.

**Comment by ascjones** [comment]
Notes from discussion with @Robbepop:

- Minimize storage access, because they are expensive (in terms of gas)
- Optimize for gas cost, not necessarily for pure efficiency, though usually they are correlated.
- Aim for a simple implementation that results in a small wasm binary size
