### ISSUE TITLE
Add storage2::Stash::remove method

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#411]
The `storage2::Stash` data structure is currently missing a method to remove elements without forcing a lookup into the storage. For example removing an element of a `storage::Stash` instance via its `take` method will potentially cause a contract storage read for the same element because `take` returns the old element if any.

This overhead cannot be avoided even if a caller is not interested into the old returned value. For the purpose of effectively avoiding the storage read we need to add a new API to the `storage2::Stash`:
```rust
fn remove(&mut self, index: Index) -> Option<()> { ... }
```
This API acts very similar to the `take` API and even still returns an `Option`. However, it guarantees to make no contract storage reads to the indexed element and will only write to its internal low-level lazy cache that the element at the given index is going to be removed at the end of the contract execution.
Calling `storage2::Stash::remove` with an index out of bounds for the `storage2::Stash` should return `None` and does not remove the element otherwise it returns `Some`.

## ToDo List

- [ ] Implement `storage2::Stash::remove`.
- [ ] Write unit tests to proof correctness of the new `storage2::Stash::remove`.
- [ ] **Bonus:** Write performance tests to show the difference between `storage2::Stash::take` and `storage2::Stash::remove`.
