### ISSUE TITLE
Wrap Wasm environment in RefCell

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#423]
Blocked by: https://github.com/paritytech/ink/pull/422

## Current State

We currently use `unsafe` and `static mut` to achieve the same effect for the global environment instance of the Wasm (on-chain) environment.
This has the advantage of being the most efficient solution with respect to not having to increment or decrement a flag upon every access to the environment but has the downside of introducing `unsafe` Rust code.

## Advantage: Avoid Heap Allocations

However, using `RefCell` for the Wasm environment brings another advantage with it:
We can utilize its `Ref` and `RefMut` abstractions to prevent heap allocations in some places.
For example we could then provide a `get_raw_storage` method to return uninterpreted or undecoded storage via `get_raw_storage(key: Key) -> Ref<[u8]>` without ever having to allocate on the contract heap.

## Example: Call Data

This is especially useful if combined with other APIs, e.g. we could use this for `CallData` used to decode a contracts input selector and arguments.
By introducing this API we could have it avoid a heap allocation that is current necessary since it needs to store the uninterpreted bits in a `Vec<u8>` right now. This means that no ink! contract can ever avoid the heap allocator entirely. However, with this change super simple contracts could completely get rid of the heap allocator which would probably safe approximately 1-2kB of Wasm file size for those contracts. In addition to that we could of course also safe the whole copying of environment buffer to the `Vec` buffer.

## Generality

We could provide such raw and uninterpreted storage accesses for a whole variety of environment APIs and thus decrease copy overhead in many situations.

## ToDo List

- [ ] Wrap the Wasm on-chain environment in `RefCell` instead of using a `static mut` instance and `unsafe` code to access it.
- [ ] Add `get_raw_contract_storage` returning a `Ref<[u8]>` to the environmental static buffer.
- [ ] Implement the improved `CallData` that is using `Ref<[u8]>` internally instead of `Vec<u8>` to avoid heap allocations and copying.
- [ ] Integrate the new `CallData` into `ink_lang` codegen.
- [ ] Test and show/proof that Wasm file sizes after the change to the new `CallData` actually improves (lowers) or stays the same. If it stays the same, analyze why it doesn't cut off the heap allocator.

**Comment by Robbepop** [comment]
In my personal research branch I was experimenting with this with the conclusion that this is far more `unsafe` and less feasible to implement than I initially though leading me to conclude that the proposed changes for `CallData` are not worth the effort.

Instead for the sake of heap memory allocator free contract dispatch adjusting the ink! code generation to generate a dispatch `enum` instead of using `CallData` yielded similar improvements to what I was expecting with the above stated idea for `CallData`.

Still wrapping the environment in `RefCell` instead of using `UnsafeCell` could yield some interesting benefits for a safer and more robust codebase if the performance regressions are minimal. This needs to be further researched though!

**Comment by Robbepop** [comment]
Concluded to be not viable. Closed.
