### ISSUE TITLE
Add ink_abi support for new ink_core::storage2 module abstractions

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#424]
When implementing the `ink_core::storage2` module and its abstractions it has been forgotten to add support for the `ink_abi` traits to properly generate smart contract metadata for the `storage` field of the JSON that tells where in contract storage certain components lie.
We eventually have to redesign this trait for the new `ink_core::storage2` module since it is no longer a requirement for storage entities to know where they are positioned in the contract storage. So a redesigned `ink_abi` trait has to provide a storage position flow as the `SpreadLayout` trait already does.

## ToDo List

- [x] Redesign the `ink_abi` trait to guide the storage position flow.
- [x] Implement the new trait for all `storage2` abstractions:
    - [x] `ink_core::storage2::lazy` module abstractions
    - [x] `ink_core::storage2::collections` module abstractions
    - [x] `ink_core::storage2::alloc` module abstractions
    - [x] `ink_core::storage2::Pack`
    - [x] `ink_core::storage2::Memory`
    - [x] All Rust primitives, array, tuples and prelude types
- [x] Make use of these new mechanics for `ink_lang` codegen.

**Comment by Robbepop** [comment]
Implemented by https://github.com/paritytech/ink/pull/422.

**Comment by Robbepop** [comment]
Closed.
