### ISSUE TITLE
Add storage2::Lazy::set method

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#426]
Currently we have no way to efficiently update the value of a `storage2::Lazy` entity.
Instead we have to mutably dereference the instance in the hopes that this won't trigger a storage read.
Adding the `Lazy::set` API is a guarantee that no storage read is ever going to occur due to update the internal value.
The `set` API must be an inherent method since `Lazy` implements `Deref` and `DerefMut` so that no methods of the inner `T` get shadowed.

## ToDo List

- [ ] Add `storage2::Lazy::set(this: &mut Self, new_value: T);` method
- [ ] Write unit tests for the new `set` API
- [ ] **Bonus:** Write benchmarks proving that the new `set` API is really more efficient than using the current `DerefMut` in some situations.
