### ISSUE TITLE
Implement Entry API for storage2::HashMap

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#427]
The current re-implementation of the `storage::HashMap` for the `storage2` module does not yet have a so-called `Entry` API.
It is important to note that only the former `storage::BTreeMap` was actually having one since the former `storage::HashMap` wasn't even a proper collection.
Since `storage2::HashMap` now is a proper collection type we can also add the `Entry` API to it inspired by the Rust standard library `Entry` API that can be found here: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry

The pros of the `Entry` API are that it allows for cleaner accesses to the underlying collection and also provides more efficient accesses in terms of calculating the hash or querying the tree or interacting with the contract storage. We really want this API back!

## ToDo List

- [ ] Implement the `Entry` API for the `storage2::HashMap`.
- [ ] Write unit tests for the new `Entry` API.
- [ ] **Bonus:** Write benchmarks showing the performance difference between `Entry` API and equivalent accesses without `Entry` API.
