### ISSUE TITLE
Move ink! example to their own repository

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#428]
**Blocked By:** https://github.com/paritytech/ink/pull/422

There is no need to keep the example contracts in this repository.
Also putting them in their own repository would force them to link their ink! crate dependencies as a user provided contract would do which should improve the situation for newcomers of Rust to better learn from these examples.

The ink! CI that uses the example contracts to test ink! for every commit could still pull the newest state of the example contracts in the CI run. This would probably incur a little bit of overhead but should be cachable for different job and also the overhead shouldn't be too large.

The move would significantly shrink the core ink! repository and keep it lean.

## ToDo List

- [ ] Create repository for the example contracts: `ink-examples`
- [ ] Find and assign an owner for the new ink! example repository
    - We want to have at least one "owner" per crate in ink! who is responsible for updating and maintaining the crate.
- [ ] Move example contracts to the new repository
    - [ ] Flipper
    - [ ] Incrementer
    - [ ] ERC-20
    - [ ] ERC-721
    - [ ] Multi Signature
    - [ ] Runtime Storage
    - [ ] Delegator
- [ ] Adjust CI to use the examples from the new repository.
    - For help please contact @TriplEight .

**Comment by TriplEight** [comment]
I'm interested to look at the structure of such a cargo project that would have only examples.

This new repository can be set as a git dependency. That wouldn't require creating a separate CI which will be a bit disconnected.
Alternatively, ink! CI can trigger another one and wait a status from it.

**Comment by Robbepop** [comment]
I no longer am sure if this is actually a good idea since it would highly decouple the process of introducing or fixing features in ink! and adjusting the ink! examples which needs to be done anyways.
