### ISSUE TITLE
Make it possible to properly attribute the storage struct

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#430]
Currently, if you put an attribute to the `#[ink(storage)]` struct (or enum) you get an error. I guess this is due to oddities in how the storage struct is actually generated in code: As type alias to another storage struct called `Storage` that is the actual storage struct.

This issue is about simplifying this codegen in order to make it more compliant with the input code. Things should not be unnecessarily complicated in ink!'s codegen since this obviously hinders implementation of normal Rust behaviour.

## ToDo List

- [ ] Change ink! code generation so that it generates code that the user would more expect from the given input. E.g. do not create a type alias to another struct but just create the struct as the user wishes it to be with all its user provided attributes etc.
- [ ] Write tests that check if attributes (e.g. derive attribute) are now working properly on the `#[ink(storage)]` struct.
- [ ] Also check if the same applies to `ink-as-dependency` code generation settings.

**Comment by Robbepop** [comment]
As found out during the implementation of https://github.com/paritytech/ink/pull/422 the old `ink_lang` code generation produced incorrect attributes on all messages, constructors and methods of the storage struct by giving them the attributes of the storage struct instead of their own attributes.
This got fixed in https://github.com/paritytech/ink/pull/422 which should also allow to properly attribute the storage struct now.

**Comment by Robbepop** [comment]
This is probably fixed by https://github.com/paritytech/ink/pull/422.

**Comment by Robbepop** [comment]
Closed since #422 got merged.
