### ISSUE TITLE
Optimize CallData for cross contract calling

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#436]
Currently the `CallData` abstraction is used to build up a buffer to cross call another contract on the chain. The building up is performed via an instance internal `Vec<u8>` buffer.
The advantage is that this implementation is easy.
The downside is that this implementation requires heap memory allocation in all cases, even in cases without any input parameters since the selector is encoded in the `Vec<u8>` buffer as well.

We can do better than this!

## Proposal

Instead of building up an ever growing internal `Vec<u8>` buffer that stores the intermediate encoded results of the selector and all encoded input parameters we could instead build up the `CallData` on the Rust type-level.
This would force the API of `CallData` to take `self` instead of `&mut self` and return another generic `CallData` instance again.

So the new `CallData` data structures would look something like this:

```rust
struct CallData<Args> {
    selector: [u8; 4],
    args: ArgumentList<Args>,
}

struct ArgumentList<(Head, Rest)> {
    head: Argument<Head>,
    rest: ArgumentList<Rest>,
}

struct Argument<'a, A> {
    arg: &'a A,
}
```

The `CallData` struct would still have its common API:

```rust
pub fn new() -> CallData<EmptyArgumentList> { ... }
pub fn push_arg<A>(self, arg: &A) -> CallData<A, Rest> { ... }
pub fn finalize(self, strategy: ?) -> Result { ... }
```

With `finalize` actually finalizing the call via some strategy to call or instantiate a smart contract given this `CallData`. This are just ideas and the base API might evolve differently though. However, the idea stays the same for our planned optimization.
Also the finalized instance implements `scale::Encode` which we can then use to simply encode into the global environmental buffer once during the call or instantiation process.

This way we only ever have to encode anything in the `finalize` step where we could use the environmental static buffer instead of building up our own buffer avoiding heap allocations all together. This is the whole point of our optimizations.

## ToDo List

- [ ] Implement the new generic `CallData` data structures
- [ ] Write tests for the new `CallData`
- [ ] There might be the need to now have 2 different `CallData` abstractions; one for calling contracts and one for storing the input call data if you have been called. They might profit from different optimization strategies. However, the other optimization should be implemented separately. It is though important to know that we might not be able to simply throw away the old `CallData` abstractions at first.
- [ ] Make sure that some cross-calling smart contract like the `Delegator` actually profit from these optimizations, e.g. in terms of gas usage or compiled Wasm file size.

**Comment by Robbepop** [comment]
Implemented by https://github.com/paritytech/ink/pull/439. Closed.
