### ISSUE TITLE
Avoid heap memory allocation for decoding input arguments

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#438]
When an ink! smart contracts is called we currently store the input buffer that is returned by the environments `input` method in a so-called `CallData` structure. This `CallData` structure simply has a `Selector` and a `Vec<u8>` field for the selector and the undecoded arguments respectively.
The advantage of this design is simplicity.
The big downside is that we require heap memory allocation for every single contract execution. Even if the entire rest of the smart contract does not need heap memory allocation at all we still have to link this huge piece of code into the final Wasm executable which is very costly especially for those small smart contracts.

Another design is to automatically generate a `CallData` `enum` via `ink_lang` macros that has a variant for every message or constructor with its selector bytes. Upon `scale::Decode` we immediately dispatch given the first four bytes and directly decode into the known types for each variant. This way we have a type safe approach that no longer requires heap memory allocation by construction.

The downside is that code generation of this `enum` has to be performed and the dispatch routines have to be rewritten. Also there might be some Wasm file size overhead due to the `enum` type definition and construction procedure.

## ToDo List

- [ ] Implement the code generation in `ink_lang/macro` in order to generate the `CallData` enum that is specific to every single contract.
    - There should be exactly one variant for every message or contructor.
    - There should be two different `enum` for messages and constructors.
    - Variant names should use their unique identifiers that we already use, e.g. for a message `foo` with selector `0x12131415` the variant name in case of messages should be something like `Message12131415` and not `MessageFoo`.
- [ ] Refactor the environmental `input` method in order to make it use a specified `type` that it is going to return back decoded from the given input bytes.
- [ ] Rewrite the dispatch routines to use the new automatically generated `enum` data structures.
- [ ] Manually test and research the consequences for the resulting Wasm file sizes before and after the change and write a conclusion.

**Comment by Robbepop** [comment]
Closed by https://github.com/paritytech/ink/pull/449.
