### ISSUE TITLE
Fix scripts/check-* and possibly rewrite them in Rust

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#455]
The `scripts/check-*` files are intended to be run before pushing/creating a PR. This is also described [here](https://github.com/paritytech/ink#scripts) in the Readme. They currently do not work though, there are some errors and some things can be removed altogether since they've become outdated.

# ToDo List

- [ ] Fix `scripts/check-*`. For `check-workspace.sh` it seems the second clippy line is just missing wasm as a target.
- [ ] We removed the distinction between all and wasm crates a while ago. Adapt the scripts accordingly.
- [ ] Remove crates which no longer exist (cli, etc.).
- [ ] **Bonus:** Rewrite these check scripts in Rust using the [std::process crate](https://doc.rust-lang.org/std/process/index.htm).

**Comment by ascjones** [comment]
I haven't ever used it, but this might be an interesting use case for https://github.com/sagiegurari/cargo-make
