### ISSUE TITLE
Implement storage2::Stash::drain_with method

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#459]
The `storage2::Stash` storage data structure has the weakness of having a pretty costly `take(index)` function since it is required to relink its left-over vacant entries in a doubly-list linked manner. Touching multiple storage entries is common.

Especially when a deep clean-up of some storage stash data structure is needed where we still need access to the cleaned-up values we are doomed to a lot of computation.
We can see usage of this in the existing `storage2::HashMap` implementation that uses `storage2::Stash` underlying for its keys. When `storage2::HashMap::drop` is called it needs exactly this kind of clean-up for the underlying storage stash.

By introducing the so-called `drain_with` API we can eliminate most of the overhead computations and focus on what really needs to be done:

```rust
impl Stash {
    pub fn drain_with<F>(&mut self, f: F)
    where
        F: FnMut(T),
    {
        // call `f` for every moved out `T`
        // at the end the storage Stash is empty and in a valid state
    }
}
```

The name `drain_with` is inferred from the standard library's `Vec::drain` method that has a very similar job.

## ToDo List

- [ ] Implement `storage2::Stash::drain_with` as shown above.
- [ ] Write unit tests to verify the correctness of `storage2::Stash::drain_with` in different use cases.
- [ ] Write benchmarks to compare the new `storage2::Stash::drain_with` against the alternative `into_iter` implementation or (even worse) a coordinated `take(at)`-loop.
- [ ] Make use of the new `storage2::Stash::drain_with` in the above mentioned `storage2::HashMap` implementation where appropriate.

**Comment by cmichi** [comment]
See #604 for why this issue was closed.
