### ISSUE TITLE
Optimize storage store/load of types that do not require SCALE encoding/decoding

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#462]
## Current State

Currently, whenever ink! performance a read or write from and to contract storage it always encodes or decodes the fetched or written instance of type `T`.
This is a generic solution that works well for all `T: scale::Encode + scale::Decode`.

However, there are types for which we know that their encoding and decoding is not required, e.g. for types that always have the same internal data layout in Wasm compilations.

- This is the case for all primitives types, especially for `i32`, `u32`, `i64` and `u64`.
- We can even go further as to also extend this rule to array-like data structures such as `Vec<T>` or `[T; N]` where `T` is any of the aforementioned types.
- Also tuples consisting of only those aforementioned "primitive" Rust types can be transmuted into their byte representation just like vectors and arrays.

So instead of encoding and decoding those types respective to their SCALE implementation we simply `transmute` then between `T` and their underlying bytes representation.
The only problem is that we therefore have to know their sizes up front, but this should be possible using Rust's `core::mem::size_of<T>`.

## Advantages

- No need to SCALE encode or decode certain types and even their vector, array and tuple representations.
- No need to copy over the bytes of such instances over to the contract's internal static 16kB scratch buffer, instead we can directly store incoming bytes into those instances or take their byte representations directly from them.

## Task & Challenges

We want to experiment with a practical implementation for ink! for this feature.
The feature must not require nightly-only features such as `specialization`.
Also the implementer has to provide benchmarks that "proof" that we avoid SCALE encoding/decoding and furthermore avoid copying into the contract's static 16kB buffer.

## ToDo List

- [ ] Implement SCALE-avoidance for reading and writing from and to contract storage for:
    - [ ] All Rust primitive types for which this is applicable, e.g. `i32` and `u64`.
    - [ ] Rust's `Vec<T>` for all `T` for which this is applicable, e.g. `Vec<i32>`.
    - [ ] Arrays (`[T; N]`) for all `T` for which this is applicable and where `N` is smaller than or equal to 32.
    - [ ] Tuples that consist only of types where this is applicable, e.g. `(i32, u64)`.
    - [ ] All combinations of the above, e.g. `Vec<[(i32, i32); 5)]>`.
- [ ] Write unit tests that check that reading and writing using the above types work for Wasm compilations.
- [ ] Write benchmarks that "proof" that the implementation described above actually has some performance advantages. Present your results.
