### ISSUE TITLE
Generalize EnvTypes to just Env, add MAX_EVENT_TOPICS constant

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#469]
In order to properly implement a compile-time check for ink! smart contracts to define not more event topics for any given user defined event than is allowed by the target smart contracts chain we need to include another constant value in our `EnvTypes` trait.
For that purpose we should also consider renaming `EnvTypes` to just `Env` or something similar since it will no longer just contain some type aliases.
With the so-called `MAX_EVENT_TOPICS` constant set in place the ink! codegen will be able to generate code in a way that checks that there are no user defined events with more topics than are allowed given this constant value.

## ToDo List

- [x] Add `MAX_EVENT_TOPICS` constant to `EnvTypes`
- [x] Rename `EnvTypes` to something that suits better, e.g. `Env` (not sure if `Env` is actually a good name here)
- [x] Implement ink! codegen to check if no user defined events has more topics than specified by `MAX_EVENT_TOPICS` constant.

**Comment by Robbepop** [comment]
Implemented. Closed.
