### ISSUE TITLE
Sync with most recent Substrate changes

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#474]
The `contracts-pallet` (Seal) has changed significantly in [this PR](https://github.com/paritytech/substrate/issues/6355).
We need to adjust ink! to incorporate adjustments for all the changes necessary to make it work with the next upcoming released version of Substrate.

This issue is soon to be extended with a detailed ToDo list to track sub-tasks for this process.

## ToDo List

- `ext_gas_price` -> `ext_weight_to_fee(ctx, gas: u64, out_ptr: u32, out_len_ptr: u32)`
- Remove `ext_scratch_read`, `ext_scratch_write` and `ext_scratch_len`.
- Add `ext_input` and use it instead of `ext_scratch_read` + `ext_scratch_len`.
- Replace scratch buffer with `(pointer, len)` tuple:
    - [ ] `ext_get_storage(ctx, key_ptr: u32, out_ptr: u32, out_len_ptr: u32) -> ReturnCode`
        - `ReturnCode::KeyNotFound`
    - [ ] `ext_transfer(account_ptr: u32, account_len: u32, value_ptr: u32, value_len: u32)`
    - [ ] `ext_call`: Add `output_ptr` and `output_len_ptr` as well as change return type to `ReturnCode`.
        ```rust
        ext_call(
            callee_ptr: u32,
            callee_len: u32,
            gas: u64,
            value_ptr: u32,
            value_len: u32,
            input_data_ptr: u32,
            input_data_len: u32,
            output_ptr: u32,
            output_len_ptr: u32
        ) -> ReturnCode
        ```
        - `ReturnCode::CalleeReverted`
        - `ReturnCode::CalleeTrapped`
    - [ ] `ext_instantiate`: Add `output_ptr` and `output_len_ptr` as well as change return type to `ReturnCode`.
        ```rust
        ext_instantiate(code_hash_ptr: u32,
            code_hash_len: u32,
            gas: u64, value_ptr: u32,
            value_len: u32,
            input_data_ptr: u32,
            input_data_len: u32,
            address_ptr: u32,
            address_len_ptr: u32,
            output_ptr: u32,
            output_len_ptr: u32,
        ) -> ReturnCode
        ```
        - `ReturnCode::CalleeReverted`
        - `ReturnCode::CalleeTrapped`
    - [ ] `ext_input(ctx, buf_ptr: u32, buf_len_ptr: u32)`
    - [ ] `ext_return(ctx, flags: u32, data_ptr: u32, data_len: u32)`
        - `lsb == 1`: `REVERT` - Revert all storage changes made by the caller.
    - [ ] `ext_caller(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_address(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_gas_left(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_balance(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_value_transferred(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_random(ctx, subject_ptr: u32, subject_len: u32, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_now(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_minimum_balance(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_tombstone_deposit(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_restore_to(dest_ptr: u32, dest_len: u32, code_hash_ptr: u32, code_hash_len: u32, rent_allowance_ptr: u32, rent_allowance_len: u32, delta_ptr: u32, delta_count: u32)`
    - [ ] `ext_deposit_event(ctx, topics_ptr: u32, topics_len: u32, data_ptr: u32, data_len: u32)`
    - [ ] `ext_rent_allowance(ctx, out_ptr: u32, out_len_ptr: u32)`
    - [ ] `ext_block_number(ctx, out_ptr: u32, out_len_ptr: u32)`

**Comment by holygits** [comment]
on a related note, is there some place to track the ink version vs. pallet-contracts version compatibility?

**Comment by Robbepop** [comment]
This is a really good question and even a bit more complex than that.
We currently have 4 different products that we somehow need to keep in sync:

- ink!
- Substrate (`contracts-pallet`)
- `cargo-contract`
- Polkadot JS Apps

If any of these is not in sync people will most probably notice.
Until now we have always targeting that the latest released versions of all components should be compatible.
In the future (post ink! 3.0) we are probably going to relax upon this to allow more freedom.
