### ISSUE TITLE
Implement Entry API for storage2::LazyHashMap

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#479]
While implementing #427 we found that the performance of the new `storage2::LazyHashMap` Entry API lacks behind our expectations. We presume that this is because the `HashMap` has to use techniques to work around the fact that `storage2::LazyHashMap` doesn't have an Entry API. Implementing the `LazyHashMap` Entry API hence should improve the performance of the `HashMap` Entry API benchmarks significantly.

## ToDo List

- [ ] Implement the Entry API for `storage2::LazyHashMap`.
- [ ] Write unit tests for the new Entry API.
- [ ] Write benchmarks showing the performance difference between Entry API and equivalent accesses without Entry API.
- [ ] Make `storage2::HashMap` use the new `storage2::LazyHashMap`.
- [ ] Run the benchmarks for the `storage2::HashMap` Entry API with and without the new `storage2::LazyHashMap` Entry API.
