### ISSUE TITLE
Migrate examples to ink! 3.0

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#485]
With ink! 3.0 we have a couple neat new storage APIs. The examples should be adapted to use those.

## ToDo

- [ ] Migrate examples to use the new `storage2::StorageHashMap` Entry API, introduced in #480 
- [ ] Migrate examples to use the new `storage2::Lazy::set(…)`, introduced in #466 
- [ ] Migrate examples to use the ops which were introduced for `storage2::Vec` in #453 
- [ ] If possible, migrate examples to use `storage2::Stash::remove_occupied(…)` introduced in #440

**Comment by Robbepop** [comment]
> If possible, migrate examples to use storage2::Stash::remove_occupied(…) introduced in #440

I am sceptical about this one since I do not want to promote `unsafe` APIs in our examples tbh.
