### ISSUE TITLE
Design & implement user friendly events

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#62]
Currently we only support depositing events through `ext_deposit_event` that takes a generic byte blob. We want to improve this situation in the regard that a user is able to specify events in their contract and deposit those in a user friendly (smart contract developer friendly) fashion.

# Road Map

- [x] Define AST for `event Foo(bar: Bar);` syntax
- [x] Implement parser for `event Foo(bar: Bar);` syntax
- [x] Implement some semantic checks for event definitions
- [x] Implement code gen for event definitions and the infrastructure around them
- [x] Implement tests to verify that things roughly work

# Example Design

```rust
contract! {
    /// Documentation for balanced changed event.
    event BalanceChanged { from: Address, to: Address, amount: Balance }
    ...
    impl MyContract {
        fn transfer_balance(to: Address, amount: Balance) {
            let from = env.caller();
            ... // perform some checks etc.
            env.emit(BalanceChanged(from, to, amount));
        }
    }
}
```

# Codegen

The code generation routine would simply collect all event definitions and put them in an `Event` enum.
Upon depositing an event the code generation would simply construct the associated `Event` variant and encode it with the given values into `ext_deposit_event`.

For the above example the generated code could look like the following:

```rust
mod events {
    use super::*;

    #[derive(parity_codec::Encode, parity_codec::Decode)]
    enum Event {
        BalanceChanged(BalanceChanged),
    }

    impl From<BalanceChanged> for Event {
        fn from(event: BalanceChanged) -> Self {
            Event::BalanceChanged(event)
        }
    }

    /// Documentation for balanced changed event.
    #[derive(parity_codec::Encode, parity_codec::Decode)]
    pub struct BalanceChanged {
        pub from: Address,
        pub to: Address,
        pub amount: Balance,
    };

    /// Guard to protect the emit event trait to be implemented externally.
    trait Sealed;

    pub trait EmitEventExt: Sealed {
        fn emit<E>(&self, event: E)
        where
            E: Into<Event>,
        {
            ext::deposit_raw_event(
                event.into().encode().as_slice()
            )
        }

        /// Do not try to implement this trait externally!
        fn sealed(sealed: Sealed);
    }

    impl EmitEventExt for pdsl_model::EnvHandler {
        fn sealed(sealed: Sealed) {}
    }
}

use events::{BalanceChanged, EmitEventExt as _};

contract! {
    ...
    impl MyContract {
        fn transfer_balance(to: Address, amount: Balance) {
            let from = env.caller();
            ... // perform some checks etc.
            env.emit(BalanceChanged{from, to, amount});
        }
    }
}
```

# Communicating to UIs

To make it possible for UIs to implement some front end for handling events we need to include them in an output file. This could be either included in the already existing API description file or in another file.

```json
{
    "name": "MyContract",
    ...
    "events": [
        {
            "name": "BalanceChanged",
            "args": [
                {
                    "name": "from",
                    "type": "Address"
                },
                {
                    "name": "to",
                    "type": "Address"
                },
                {
                    "name": "amount",
                    "type": "Balance"
                }
            ]
        }
    ]
}
```

**Comment by xlc** [comment]
Can we avoid making up new syntax as much as possible?
My suggestion
```
#[derive(Events)]
enum MyEvents {
    BalanceChanged { from: Address, to: Address, amount: Balance }
};
contract! {
    type Events = MyEvents;
    ...
    impl MyContract {
        fn transfer_balance(to: Address, amount: Balance) {
            let from = env.caller();
            ... // perform some checks etc.
            Self::deposit_event(MyEvents::BalanceChanged { from, to, amount });
        }
    }
}
```

**Comment by Robbepop** [comment]
Of course we can do that as well but what is the exact advantage of excluding them in the macro or the exact disadvantage or having them inside `contract!` macro and thus as new syntax?

**Comment by xlc** [comment]
Unless the goal is allow non Rust developer to develop contract in `pDSL` by inventing a new syntax that is easier to lean than Rust, without to learn Rust, it is better to not invent new syntax. (Which I think is a non feasible goal, you can never write high quality and secure contract using Rust without actually understanding the Rust language).

This is just feedback from me and many other developers I work with when dealing with Substrate macros.
Learning Rust is already hard enough, but leaning another new syntax (with poor documentation currently) on top it, is even harder.

I had some experiences with C++ DSL (boost spirit) and it is bad. I feel I was writing a new language in C++ and I do not have the support of C++ tools (how do you step into an overloaded operator `+`?, in this case, you can't step into a macro generated function). Neither I have support of this new language just because it have a much limited community and hence resources.
When there is a syntax error in macro, it is almost impossible for a beginner to figure out how to resolve it. It is a lot of work to have Rust macro provide a detailed error. You will have hard time support all the people struggling with the macro syntax and there won't be any tools to help.

The goal for `pDSL` (I hope) is not able to writing contract with least amount of code (we are not playing a code golf contest), but instead provide a robust, secure and flexible framework to write contracts with a gentle learning curve (for new Rust developers).
Macro can be used to hide details about contract inner workings, but please do not use it to replace Rust features.

**Comment by gavofyork** [comment]
Actually, the primary goal of pDSL is to provide a language---related to Rust, but *not* Rust---that is as expressive for authoring contracts as possible. If that means straying from the Rust grammar at the structural level, then so be it. Conciseness, taken in terms of specifically how simple the grammar is to express common concepts, is pretty much the same as its domain expressivity.

Documentation is lacking as this is still in the research phase. Once the language reaches MVP, it will be attended to.

For those who prefer to stay as close to Rust as possible there are two other layers, one of which uses no macros (or almost none) and is accordingly terse and the other (`model`) which uses limited macros and provides a middle ground.

I actually quite liked Boost.

**Comment by Robbepop** [comment]
Implemented by https://github.com/paritytech/ink/pull/78.
Can be closed as soon as https://github.com/paritytech/ink/pull/78 is merged.
