### ISSUE TITLE
Implement `seal_call_runtime`

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#854]
With https://github.com/paritytech/substrate/pull/9276 implemented, we can now introduce `seal_call_runtime` into ink!, providing contracts with the ability of dispatching calls into the runtime.

## ToDo

- [ ] Add a new ink! API function `self.env().call_runtime(…)` analog to our other `env()` API functions (e.g. with UI tests under `crates/lang/macro/tests/ui/`). See the linked issue for the `contracts` pallet API.
- [ ] Add an example which demonstrates how to call into the runtime. It should be possible to do this analog to the `rand-extension` example.
- [ ] Implement a test for this new example in the [ink-waterfall](https://gitlab.parity.io/parity/ink-waterfall).
- [ ] Add a section to the [ink-docs](https://github.com/paritytech/ink-docs), describing how this new functionality can be used.

**Comment by athei** [comment]
You have to keep in mind that extrinsics cannot return any data (only success/fail). They communicate via events with the offchain world. So something like `rand-extension` isn't possible with `seal_call_runtime`. It is unstable for a reason. There are several open questions around it:

- Is it OK that it can't return data or should we make an effort to deliver events (asynchronously) to contracts?
- There are issues around stability. Contract APIs must be stable but extrinsics are allowed to change. Once you allow some extrinsic to be called from a contract it puts a heavy burden on the runtime to never change this API.

**Comment by athei** [comment]
Explained [here](https://github.com/paritytech/substrate/blob/abeea6d04d72eddb136ec494298035977c9cdbe4/frame/contracts/src/wasm/runtime.rs#L1691-L1701).
