### ISSUE TITLE
Rename `name` in metadata to `label`

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#900]
In our metadata we currently have a `name` Array field for constructors, messages and arguments.

There are some issues with it:

* Contrary to the term it is not actually any kind of identifier. This field does not have any impact on contract execution, it is used purely for display purposes in the UI's.
* We have a field `selector` which actually serves as the identifier. There is some concern that users will mistakenly assume that the `name` has some implication for the contract execution. Hence renaming it to `label` would clarify this.
* For traits, ink! generates a field in the form of `"name": ["BaseErc20", "new"]`. The `BaseErc20` hereby is a trait implemented by the contract. This exposes internal implementation details of the contract without the developer having any influence over it.
* Right now it's not clear how a UI is supposed to handle the different elements in an Array. Concatenate them? How? Having a String would also simplify that.

Recently there was the PR https://github.com/paritytech/ink/pull/859 by @xgreenx where the need for influencing this value in the metadata was also stated.

My proposal is this:
* Rename `name` to `label` for constructors, messages and arguments.
* Make it a String instead of an Array.
* For traits, default to the form `BaseErc20::new` as String.

I'm creating this issue to start a discussion on this. It would be great if especially @seanyoung could give his opinion.

If we decide to do this these would need to be done:

## ToDo

- [ ] Rename `name` to `label` for constructors, messages and arguments.
- [ ] Make it a String instead of an Array.
- [ ] Revive https://github.com/paritytech/ink/pull/859, but with `label` instead of `metadata_name`. I would leave the possibility of modifying the arguments labels out for now.
- [ ] Create follow-up issues for Canvas UI and polkadot-js.

**Comment by seanyoung** [comment]
- Should be there be defined upgrade path for polkadot-js/Canvas UI? Something like: try `label` first, else fall back to `name`. Or will just this change from one version to the next?
- Making this a string rather than an array is a good thing, I think.

**Comment by cmichi** [comment]
>Should be there be defined upgrade path for polkadot-js/Canvas UI? Something like: try label first, else fall back to name. Or will just this change from one version to the next?

Good point and good idea! We should specify this fallback in the follow-up issues for the UI's.

**Comment by xgreenx** [comment]
I agree with everything=) 
The string will be more clear for developers instead of the array. If they want, they can easily split it with `::`.
`label` is more descriptive than `name`.

I can rework https://github.com/paritytech/ink/pull/859 and add `label`, string instead of the array. Do I need to add support for changing the name of the arguments?

Something like that:
```rust
    #[ink(message)]
    #[ink(label = "my_ balance_of")]
    fn balance_of(&self, #[ink(label = "my_owner")] owner: AccountId) -> u32 {
        self.get().owned_tokens_count.get(&owner).cloned().unwrap_or(0)
    }
```

Or it will be implemented later?

**Comment by cmichi** [comment]
>I agree with everything=)

Good to hear :-)!

>I can rework #859 and add label, string instead of the array.

That would be awesome!

>Do I need to add support for changing the name of the arguments?

No, let's leave it out for now.

**Comment by HCastano** [comment]
Closed via #923
