### ISSUE TITLE
Wasm file size reduction: Library Components

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#949]
Below is a list of isolated actionable items that may reduce the Wasm file size of certain ink! smart contracts if applied correctly and thoroughly throughout the ink! codebase and codegen.

# Todo List

    - [ ] Retire `ToAccountId` and replace with `AsRef<AccountId>`.
        - Returning a reference instead of a value type is important for `AccountId` types which are usually 256-bits in size
          and therefore too big to be efficiently computed by a Wasm VM.
    - [ ] Make `EnvAccess` API use references as inputs to big environmental types such as `AccountId`.
    - [ ] Make `ink_env::CallBuilder` API use references as inputs to big environmental types such as `AccountId`.

**Comment by Robbepop** [comment]
I began working on:

> Make ink_env::CallBuilder API use references as inputs to big environmental types such as AccountId.

However, it is a bit unfortunate to work on it before #665 has been merged since most of the work for the ink! codegen has to be redone there. I am not done entirely but already see some improvements for the Delegator example contract.
