### ISSUE TITLE
Add example which demonstrates difference in behavior of return type `Result` for contracts

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink#956]
This is a follow-up to https://github.com/paritytech/ink/pull/665.

We should create an example to illustrate how revert-on-`Err` works. The example should especially highlight that `Result` behaves different if returned from a root contract vs. returned from child contracts.

## ToDo

- [ ] For this purpose the example should have root and a child contract: The child contract should expose a message that returns a `Result`. The root contract should have a message returning `Result` as well.
- [ ] The comments should highlight that in the case of root returning `Err` a revert will happen, whereas for the child contract's `Result` return no revert will happen.
- [ ] As a follow-up: create an issue in [`ink-waterfall`](https://github.com/paritytech/ink-waterfall) to test this new example.
